language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -e ".[test]"

script:
  - py.test graphene_federation --cov=graphene_federation -vv

after_success:
  - pip install coveralls
  - coveralls

stages:
  - test
  - integration-test
  - linting


jobs:
  include:
    - stage: linting
      python: 3.7
      install:
        - pip install -e ".[dev]"
      script:
        - black graphene_federation --check
    - stage: integration-test
      services:
        - docker
      script:
        - make integration-build
        - make integration-test
